sonar.organization=futurmasterdev

sonar.projectKey=futurmasterdev_plns-or-pipeline
sonar.projectName=[PLNS] OR Pipeline
sonar.projectVersion=0.0.0
sonar.verbose=true

sonar.sources=src/
sonar.tests=src/test/src

sonar.exclusions=src/app/src/**,src/test/**
sonar.coverage.exclusions=src/app/src/**,src/test/**,src/lib/src/dto/**,src/lib/src/bo/**
sonar.cpd.exclusions=src/app/src/**,src/test/**
sonar.test.exclusions=src/app/src/**,src/test/**

sonar.cfamily.compile-commands=compilation-databases/Debug/compile_commands.json
sonar.coverageReportPaths=compilation-databases/sonarqube.xml
sonar.cfamily.valgrind.reportsPaths=compilation-databases/**memcheck-results.xml
